export default function handler(req, res) {
  res.status(200).json(
    [
      {
      id: "1",
      name: "미자드",
      icon: "",
      rarity: "6",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
      chain_skill: {
        name: "성큰 스파인",
        first: {
          tiles : "4",
          damage : "165%",
          area : "2 circle",
          area_type : "circle",
          text : "주변 2서클 내의 적 3체에 165 %의 데미지를 준다",
        },
        second: {
          tiles : "8",
          damage : "170%",
          area : "3 circle",
          area_type : "circle",
          text : "주변 3서클 내의 적 3체에 170 %의 데미지를 준다",
        },
        third: {
          tiles : "13",
          damage : "180%",
          area : "3 circle",
          area_type : "circle",
          text : "주변 3서클 내의 적 3체에 180 %의 데미지를 준다",
        },
      },
      active_skill: {
        name: "",
        text: "",
        type: {},
      },
      equip_skill: {
        name: "",
        text: "",
        type: {},
      },
      breakthrough: {
        first:{},
        second:{},
        third:{},
        fourth:{},
        fifth:{},
        sixth:{},
      },
      faction: "",
      porsonality: "",    
      voice: {
        japan : ""
      },
      birthday: "",
      sex: "",
      height:"",
    },
    {
      id: "2",
      name: "5migard",
      rarity: "5",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
    },
    {
      id: "3",
      name: "4migard",
      rarity: "4",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
    },
    {
      id: "4",
      name: "6karen",
      rarity: "6",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer",
    },
    {
      id: "5",
      name: "3karen",
      rarity: "3",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer", 
    },
    {
      id: "46",
      name: "4karen",
      rarity: "4",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer",
    },
    {
      id: "44",
      name: "6migard",
      rarity: "6",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
    },
    {
      id: "42",
      name: "5migard",
      rarity: "5",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
    },
    {
      id: "41",
      name: "4migard",
      rarity: "4",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "sniper",
    },
    {
      id: "40",
      name: "블랑",
      rarity: "4",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer",
    },
    {
      id: "39",
      name: "3karen",
      rarity: "3",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer", 
    },
    {
      id: "38",
      name: "4karen",
      rarity: "4",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer",
    },
    {
      id: "37",
      name: "라파엘",
      rarity: "6",
      main_attribute: "water",
      sub_attribute: "water",
      class: "supporter",
    },
    {
      id: "36",
      name: "펙트",
      rarity: "5",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "changer",
    },{
      id: "35",
      name: "가브리엘",
      rarity: "6",
      main_attribute: "forest",
      sub_attribute: "forest",
      class: "changer",
    },
    {
      id: "34",
      name: "샤리",
      rarity: "6",
      main_attribute: "water",
      sub_attribute: "water",
      class: "changer",
    },
    {
      id: "33",
      name: "카론",
      rarity: "6",
      main_attribute: "fire",
      sub_attribute: "forest",
      class: "burster",
    }
    
    

  ]   
)
}

