
export const CharacterState = {
  id: "3333",
  name: "",
  name_alphabet: "",
  state: {
    atk: "",
    def: "",
    hp: "",
  },
  icon: "/none",
  rarity: "",
  main_attribute: "",
  main_attribute_icon:"/none",
  sub_attribute: "",
  sub_attribute_icon:"/none",
  class: "",
  class_icon:"/none",
  faction: "",
  faction_icon: "/none",
  chain_skill: {
    name: "",
    icon: "/none",
    first: {
      tiles : "",
      damage : "",
      area : "",
      area_type : "",
      text : "",
    },
    second: {
      tiles : "",
      damage : "",
      area : "",
      area_type : "",
      text : "",
    },
    third: {
      tiles : "",
      damage : "",
      area : "",
      area_type : "",
      text : "",
    },
  },
  active_skill: {
    name: "",
    text: "",
    icon: "/none",
  },
  equip_skill: {
    name: "",
    text: "",
    type: {},
    icon: "/none",
  },
  breakthrough: {
    first:{},
    second:{},
    third:{},
    fourth:{},
    fifth:{},
    sixth:{},
  },

  equip:{
    name: "스피널 블",
    image: "/SearchC",
    lv1_text: "연쇄 추가로 1회 입힌다.",
    lv3_text: "연쇄 가로 1회 입힌다.",
    lv6_text: "연쇄 가로 1회 입힌다.",
    lv10_text: "연쇄추가로 1회 입힌다.",
    lv1_state_text: "",
    lv2_state_text: "",
    lv4_state_text: "",
    lv5_state_text: "",
    lv7_state_text: "",
    lv8_state_text: "",
    lv9_state_text: "",
  },

  ascension: {
    lv1: "",
    lv2: "",
    lv3: "",
  },
  faction: {
    name: "",
    big_gift: "",
    small_gift: "",
  },
  porsonality: {
    name: "",
    big_gift: "",
    small_gift: "",
  },    
  voice: "",
  birthday: "",
  sex: "",
  height:"",
  singularity:"",
  file:{
    name: "미자드",
    nickname: "성큰 스파인",
    gender: "여",
    height: "183cm",
    birthday: "1월 30일",
    birthplace: "자난 성",
    element: "숲",
    affilition: "일루미나 연방",
    fighting_style: "스파인 블레이드, 성큰 스파인"
  },
}

export default CharacterState;